In [1]:
import numpy as np
import torch
torch.manual_seed(1)

# base Tensor

In [2]:
x = torch.Tensor(2,2)
x

tensor([[-1.5879e+38,  4.5688e-41],
        [-1.5879e+38,  4.5688e-41]])

In [3]:
x.type(), x.size(), x.numel()

('torch.FloatTensor', torch.Size([2, 2]), 4)

In [4]:
x2 = torch.Tensor(4,3,2,1)
x2

tensor([[[[2.3607e-09],
          [1.6521e-07]],

         [[1.3445e+22],
          [1.7062e-07]],

         [[1.7586e-04],
          [2.0315e+20]]],


        [[[1.6893e-07],
          [1.3177e-08]],

         [[2.4718e-18],
          [1.9421e+31]],

         [[2.7491e+20],
          [6.1949e-04]]],


        [[[7.1856e+22],
          [4.3605e+27]],

         [[2.3329e-18],
          [1.9284e+31]],

         [[3.2314e-18],
          [3.3198e-09]]],


        [[[2.5962e+20],
          [1.0617e+21]],

         [[1.0489e-08],
          [4.3919e-05]],

         [[1.6852e+22],
          [2.0913e+20]]]])

In [5]:
x2.type(), x2.size(), x2.numel()

('torch.FloatTensor', torch.Size([4, 3, 2, 1]), 24)

# Other methods to make Tensor

In [6]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
torch.ones(4,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
torch.eye(4,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [9]:
torch.rand(4,4), torch.randn(4,4)

(tensor([[0.7576, 0.2793, 0.4031, 0.7347],
         [0.0293, 0.7999, 0.3971, 0.7544],
         [0.5695, 0.4388, 0.6387, 0.5247],
         [0.6826, 0.3051, 0.4635, 0.4550]]),
 tensor([[-0.6970, -1.1608,  0.6995,  0.1991],
         [ 0.8657,  0.2444, -0.6629,  0.8073],
         [ 1.1017, -0.1759, -2.2456, -1.4465],
         [ 0.0612, -0.6177, -0.7981, -0.1316]]))

In [10]:
x3 = torch.arange(0, 3, step=0.3)
x3

tensor([0.0000, 0.3000, 0.6000, 0.9000, 1.2000, 1.5000, 1.8000, 2.1000, 2.4000,
        2.7000])

In [11]:
x3.size()

torch.Size([10])

In [12]:
torch.Tensor([[6,2],[3,4],[5,6]])

tensor([[6., 2.],
        [3., 4.],
        [5., 6.]])

In [13]:
numpy_test = np.array([[5,6],[10,11]])
torch.from_numpy(numpy_test)

tensor([[ 5,  6],
        [10, 11]])

# Use Python array function to make Tensor

In [14]:
x4 = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
x4

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [15]:
x4[0:2,:]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [16]:
x4[1]

tensor([4., 5., 6.])

In [17]:
x4[0,:]

tensor([1., 2., 3.])

In [18]:
x4[0:1,:] = torch.Tensor([62,72,80])
x4

tensor([[62., 72., 80.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]])

In [19]:
x4[1] = torch.Tensor([200,78, 89])
x4

tensor([[ 62.,  72.,  80.],
        [200.,  78.,  89.],
        [  7.,   8.,   9.]])

In [20]:
x5 = torch.split(x4, 1, dim=0)

In [21]:
torch.cat(x5, dim=1)

tensor([[ 62.,  72.,  80., 200.,  78.,  89.,   7.,   8.,   9.]])

In [22]:
x6 = torch.randn(3,3)

mask  = torch.ByteTensor([[1,0,0],[1,1,1],[0,1,0]]).bool()

out = torch.masked_select(x6, mask)

x6, mask, out

(tensor([[-0.4212, -0.5107, -1.5727],
         [-0.1232,  3.5870, -1.8313],
         [ 1.5987, -1.2770,  0.3255]]), tensor([[ True, False, False],
         [ True,  True,  True],
         [False,  True, False]]), tensor([-0.4212, -0.1232,  3.5870, -1.8313, -1.2770]))

# Reshaping on dimension of Tensor

In [23]:
x7 = torch.zeros(2,2,1)
x7

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])

In [24]:
x7.view(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [25]:
x7.view(-1) # -1 = Automatic

tensor([0., 0., 0., 0.])

In [26]:
x7.view(-1,2)

tensor([[0., 0.],
        [0., 0.]])

In [27]:
x7.view(4)

tensor([0., 0., 0., 0.])

In [28]:
x8 = x7.squeeze()
x7, x8

(tensor([[[0.],
          [0.]],
 
         [[0.],
          [0.]]]), tensor([[0., 0.],
         [0., 0.]]))

In [29]:
x8.unsqueeze(0)

tensor([[[0., 0.],
         [0., 0.]]])

# Calculation

In [30]:
x9 = torch.FloatTensor([[10,20,30],[40,50,60]])
x10 = torch.FloatTensor([[1,2,3],[4,5,6]])
x9

tensor([[10., 20., 30.],
        [40., 50., 60.]])

In [31]:
x10

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [32]:
x9  + x10

tensor([[11., 22., 33.],
        [44., 55., 66.]])

In [33]:
x9.add(x10)

tensor([[11., 22., 33.],
        [44., 55., 66.]])

In [34]:
torch.add(x9, x10)

tensor([[11., 22., 33.],
        [44., 55., 66.]])

In [35]:
x10.sub(x9)

tensor([[ -9., -18., -27.],
        [-36., -45., -54.]])

In [36]:
x9.sub(x10)

tensor([[ 9., 18., 27.],
        [36., 45., 54.]])

In [37]:
x9 * x10

tensor([[ 10.,  40.,  90.],
        [160., 250., 360.]])

In [38]:
x10.mul(x9)

tensor([[ 10.,  40.,  90.],
        [160., 250., 360.]])

In [39]:
torch.mul(x10,x9)

tensor([[ 10.,  40.,  90.],
        [160., 250., 360.]])

In [40]:
x10 * 10

tensor([[10., 20., 30.],
        [40., 50., 60.]])

In [41]:
x10.min()

tensor(1.)

In [42]:
x10.min(0)

torch.return_types.min(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))

In [43]:
x10.min(1)

torch.return_types.min(
values=tensor([1., 4.]),
indices=tensor([0, 0]))

In [44]:
x14 = torch.randn(3, 4)
v = torch.randn(4)
x14, v

(tensor([[-0.4791,  1.3790,  2.5286,  0.4107],
         [-0.9880, -0.9081,  0.5423,  0.1103],
         [-2.2590,  0.6067, -0.1383,  0.8310]]),
 tensor([-0.2477, -0.8029,  0.2366,  0.2857]))

In [45]:
x14@v

tensor([-0.2730,  1.1337,  0.2771])

In [48]:
x15 = torch.randn(3,4)
u, s, v = torch.svd(x15)
x15, u, s, v

(tensor([[ 1.1341, -1.1115,  0.3501, -0.7703],
         [-0.1473,  0.6272,  1.0935,  0.0939],
         [ 1.2381, -1.3459,  0.5119, -0.6933]]),
 tensor([[-0.6596, -0.0573, -0.7494],
         [ 0.1312, -0.9906, -0.0397],
         [-0.7401, -0.1246,  0.6609]]),
 tensor([2.7206, 1.2331, 0.1472]),
 tensor([[-0.6188, -0.0595, -0.1753],
         [ 0.6659, -0.3162, -0.5532],
         [-0.1714, -0.9463,  0.2210],
         [ 0.3799,  0.0304,  0.7838]]))